// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eamugezpwnuwjfynhynf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhbXVnZXpwd251d2pmeW5oeW5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NjQzODYsImV4cCI6MjA3NDI0MDM4Nn0.9l2N4-cinrBWyoCTciZ7uZe-OMOlqT1CXLtgijLheaQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});